using System.ComponentModel;
using CopilotSessionPersistencePoc.Copilot;
using GitHub.Copilot;
using Microsoft.Extensions.AI;

namespace CopilotSessionPersistencePoc.Execution;

public sealed class PythonExecutionToolProvider(
    PythonExecutionCoordinator coordinator)
    : ICopilotToolProvider
{
    public IReadOnlyList<AIFunction> CreateTools(string sessionId) =>
    [
        CopilotTool.DefineTool(
            async (ToolInvocation invocation, CancellationToken cancellationToken) =>
            {
                EnsureSession(invocation, sessionId);
                return await coordinator.ListArtifactsAsync(
                    sessionId,
                    cancellationToken);
            },
            toolOptions: new CopilotToolOptions
            {
                Defer = CopilotToolDefer.Never,
                SkipPermission = true,
            },
            factoryOptions: new AIFunctionFactoryOptions
            {
                Name = "list_artifacts",
                Description =
                    "List files uploaded to or generated by the current chat session. "
                    + "Use artifactId/fileName values as execute_python inputs.",
            }),
        CopilotTool.DefineTool(
            async (
                [Description("Python source code to run.")] string code,
                [Description(
                    "Artifact references in artifactId/fileName format to upload into /mnt/data.")]
                string[]? inputFiles,
                ToolInvocation invocation,
                CancellationToken cancellationToken) =>
            {
                EnsureSession(invocation, sessionId);
                return await coordinator.ExecuteAsync(
                    sessionId,
                    invocation.ToolCallId,
                    code,
                    inputFiles,
                    cancellationToken);
            },
            toolOptions: new CopilotToolOptions
            {
                Defer = CopilotToolDefer.Never,
            },
            factoryOptions: new AIFunctionFactoryOptions
            {
                Name = "execute_python",
                Description =
                    "Run Python in an isolated Azure Container Apps dynamic session. "
                    + "Read inputs from /mnt/data and write result files to /mnt/data.",
            }),
    ];

    private static void EnsureSession(ToolInvocation invocation, string expectedSessionId)
    {
        if (!string.Equals(
            invocation.SessionId,
            expectedSessionId,
            StringComparison.Ordinal))
        {
            throw new InvalidOperationException(
                "The tool invocation does not belong to the active session.");
        }

        ArgumentException.ThrowIfNullOrWhiteSpace(invocation.ToolCallId);
    }
}
